config/routes.rb
Rails.application.routes.draw do
  resources :values
  resources :themes
  resources :images
  resources :users

  # work
  match 'work',             to: 'work#index',                  via: 'get'
  match 'choose_theme',     to: 'work#choose_theme',      via: :get
  match 'display_theme',    to: 'work#display_theme',      via: :post

  get 'main/index'
  get 'main/help'
  get 'main/contacts'
  get 'main/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'work#index'
  # root 'main#index'
  #
  get "Earth.png" => "work#index"
end

app/models/value.rb
class Value < ApplicationRecord
  belongs_to :user

  validates :values, comparison: { greater_than: 0 }
end

app/controllers/values_controller.rb
class ValuesController < ApplicationController
  before_action :set_value, only: %i[ show edit update destroy ]

  # GET /values or /values.json
  def index
    @values = Value.all
  end

  # GET /values/1 or /values/1.json
  def show
  end

  # GET /values/new
  def new
    @value = Value.new
  end

  # GET /values/1/edit
  def edit
  end

  # POST /values or /values.json
  def create
    @value = Value.new(value_params)

    respond_to do |format|
      if @value.save
        format.html { redirect_to value_url(@value), notice: "Value was successfully created." }
        format.json { render :show, status: :created, location: @value }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /values/1 or /values/1.json
  def update
    respond_to do |format|
      if @value.update(value_params)
        format.html { redirect_to value_url(@value), notice: "Value was successfully updated." }
        format.json { render :show, status: :ok, location: @value }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /values/1 or /values/1.json
  def destroy
    @value.destroy!

    respond_to do |format|
      format.html { redirect_to values_url, notice: "Value was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_value
      @value = Value.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def value_params
      params.require(:value).permit(:user_id, :value, :image_id)
    end
end

app/helpers/values_helper.rb
module ValuesHelper
end

app/views/values/_form.html.haml
= form_with(model: value) do |form|
  - if value.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(value.errors.count, "error")
        prohibited this value from being saved:
      %ul
        - value.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :user_id, style: "display: block"
    = form.number_field :user_id
  %div
    = form.label :value, style: "display: block"
    = form.number_field :value
  %div
    = form.label :image_id, style: "display: block"
    = form.number_field :image_id
  %div
    = form.submit

app/views/values/_value.html.haml
%div{:id => "#{dom_id value}"}
  %p
    %strong User:
    = value.user_id
  %p
    %strong Value:
    = value.value
  %p
    %strong Image:
    = value.image_id

app/views/values/edit.html.haml
%h1 Editing value
= render "form", value: @value
%br/
%div
  = link_to "Show this value", @value
  |
  \#{link_to "Back to values", values_path}

app/views/values/index.html.haml
%p{:style => "color: green"}= notice
%h1 Values
#values
  - @values.each do |value|
    = render value
    %p
      = link_to "Show this value", value
= link_to "New value", new_value_path

app/views/values/new.html.haml
%h1 New value
= render "form", value: @value
%br/
%div
  = link_to "Back to values", values_path

app/views/values/show.html.haml
%p{:style => "color: green"}= notice
= render @value
%div
  = link_to "Edit this value", edit_value_path(@value)
  |
  \#{link_to "Back to values", values_path}
  
  \#{button_to "Destroy this value", @value, method: :delete}