config/routes.rb
Rails.application.routes.draw do
  resources :values
  resources :themes
  resources :images
  resources :users

  # work
  match 'work',             to: 'work#index',                  via: 'get'
  match 'choose_theme',     to: 'work#choose_theme',      via: :get
  match 'display_theme',    to: 'work#display_theme',      via: :post

  get 'main/index'
  get 'main/help'
  get 'main/contacts'
  get 'main/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'work#index'
  # root 'main#index'
  #
  get "Earth.png" => "work#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :values, dependent: :destroy

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token =
      User.encrypt(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    # error_explanation
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label t('.name')
    = f.text_field :name
  .field
    = f.label t('.email')
    = f.text_field :email
  .field
    = f.label t('.password')
    = f.password_field :password
  .field
    = f.label t('.password_confirmation')
    = f.password_field :password_confirmation

  .actions
    = f.submit 'Save'
    = f.submit t(".create_account"), class: "btn btn-large btn-primary"

app/views/users/_user.html.haml
%div{:id => "#{dom_id user}"}
  %p
    %strong Name:
    = user.name
  %p
    %strong Email:
    = user.email
  %p
    %strong Password:
    = user.password_digest

app/views/users/edit.html.haml
%h1 Editing user
= render "form", user: @user
%br/
%div
  = link_to "Show this user", @user
  |
  \#{link_to "Back to users", users_path}

app/views/users/index.html.haml
%p{:style => "color: green"}= notice
%h1 Users
#users
  - @users.each do |user|
    = render user
    %p
      = link_to "Show this user", user
= link_to "New user", new_user_path

app/views/users/new.html.haml
%h1 New user
= render "form", user: @user
%br/
%div
  = link_to "Back to users", users_path

app/views/users/show.html.haml
.show_user
  .row
    %aside.span4
      %section
        %h1
          = gravatar_for @user
          = @user.name

  %p
    %b= t('.email')
    = @user.email

  = link_to t('.work'), work_path, class: "btn btn-lg btn-primary"